const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('listenk', {
  onToggleRecord: (cb) => ipcRenderer.on('toggle-record', cb),
  onCancelRecord: (cb) => ipcRenderer.on('cancel-record', cb),
  transcribe: (payload) => ipcRenderer.invoke('transcribe', payload),
  paste: (text) => ipcRenderer.invoke('paste-text', text),
  setState: (state) => ipcRenderer.invoke('set-state', state),
  getStatus: () => ipcRenderer.invoke('get-status'),
  openSettingsPane: (pane) => ipcRenderer.invoke('open-settings-pane', pane),
  requestMic: () => ipcRenderer.invoke('request-mic'),
  openUrl: (url) => ipcRenderer.invoke('open-url', url),
  showInFinder: (p) => ipcRenderer.invoke('show-in-finder', p),
  clipboardWrite: (text) => ipcRenderer.invoke('clipboard-write', text),
  historyList: (limit) => ipcRenderer.invoke('history-list', limit),
  historyAppend: (entry) => ipcRenderer.invoke('history-append', entry),
  historyClear: () => ipcRenderer.invoke('history-clear'),
  statsGet: () => ipcRenderer.invoke('stats-get'),
  statsRecordTranscribe: (payload) => ipcRenderer.invoke('stats-record-transcribe', payload),
  statsRecordOllama: (payload) => ipcRenderer.invoke('stats-record-ollama', payload),
  statsClear: () => ipcRenderer.invoke('stats-clear'),
  listWhisperModels: () => ipcRenderer.invoke('list-whisper-models'),
  setWhisperModel: (name) => ipcRenderer.invoke('set-whisper-model', name),
  getEngine: () => ipcRenderer.invoke('get-engine'),
  setEngine: (engine) => ipcRenderer.invoke('set-engine', engine),
  getOllamaModel: () => ipcRenderer.invoke('get-ollama-model'),
  setOllamaModel: (name) => ipcRenderer.invoke('set-ollama-model', name),
  getOpenAiKey: () => ipcRenderer.invoke('get-openai-key'),
  setOpenAiKey: (key) => ipcRenderer.invoke('set-openai-key', key),
  getOpenAiModel: () => ipcRenderer.invoke('get-openai-model'),
  setOpenAiModel: (name) => ipcRenderer.invoke('set-openai-model', name),
  getUiLocale: () => ipcRenderer.invoke('get-ui-locale'),
  setUiLocale: (loc) => ipcRenderer.invoke('set-ui-locale', loc),
  getTheme: () => ipcRenderer.invoke('get-theme'),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  getOnboardingDone: () => ipcRenderer.invoke('get-onboarding-done'),
  setOnboardingDone: (v) => ipcRenderer.invoke('set-onboarding-done', v),
  setOnboardingHotkeyTest: (v) => ipcRenderer.invoke('set-onboarding-hotkey-test', v),
  onOnboardingHotkeyFired: (cb) => ipcRenderer.on('onboarding-hotkey-fired', () => cb()),
  ollamaList: () => ipcRenderer.invoke('ollama-list'),
  ollamaPull: (name) => ipcRenderer.invoke('ollama-pull', name),
  ollamaPullCancel: (name) => ipcRenderer.invoke('ollama-pull-cancel', name),
  ollamaDelete: (name) => ipcRenderer.invoke('ollama-delete', name),
  onOllamaPullProgress: (cb) => ipcRenderer.on('ollama-pull-progress', (_e, data) => cb(data)),
  getHotkey: () => ipcRenderer.invoke('get-hotkey'),
  setHotkey: (mode) => ipcRenderer.invoke('set-hotkey', mode),
  setLanguage: (lang) => ipcRenderer.invoke('set-language', lang),
  getLanguage: () => ipcRenderer.invoke('get-language'),
  getMode: () => ipcRenderer.invoke('get-mode'),
  setMode: (mode) => ipcRenderer.invoke('set-mode', mode),
  getTone: () => ipcRenderer.invoke('get-tone'),
  setTone: (tone) => ipcRenderer.invoke('set-tone', tone),
  getTranslateTarget: () => ipcRenderer.invoke('get-translate-target'),
  setTranslateTarget: (target) => ipcRenderer.invoke('set-translate-target', target),
  getStreaming: () => ipcRenderer.invoke('get-streaming'),
  setStreaming: (enabled) => ipcRenderer.invoke('set-streaming', enabled),
  onStreamPartial: (cb) => ipcRenderer.on('stream-partial', (_e, text) => cb(text)),
  onStreamFinal: (cb) => ipcRenderer.on('stream-final', (_e, text) => cb(text)),
  onStreamError: (cb) => ipcRenderer.on('stream-error', (_e, msg) => cb(msg)),
  onStreamReady: (cb) => ipcRenderer.on('stream-ready', () => cb()),
  onToast: (cb) => ipcRenderer.on('toast', (_e, msg) => cb(msg)),
  onNavigatePage: (cb) => ipcRenderer.on('navigate-page', (_e, id) => cb(id)),
});
