const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('listenk', {
  onToggleRecord: (cb) => ipcRenderer.on('toggle-record', cb),
  onCancelRecord: (cb) => ipcRenderer.on('cancel-record', cb),
  transcribe: (payload) => ipcRenderer.invoke('transcribe', payload),
  paste: (text) => ipcRenderer.invoke('paste-text', text),
  setState: (state) => ipcRenderer.invoke('set-state', state),
  getStatus: () => ipcRenderer.invoke('get-status'),
  openSettingsPane: (pane) => ipcRenderer.invoke('open-settings-pane', pane),
  requestMic: () => ipcRenderer.invoke('request-mic'),
  openUrl: (url) => ipcRenderer.invoke('open-url', url),
  showInFinder: (p) => ipcRenderer.invoke('show-in-finder', p),
  clipboardWrite: (text) => ipcRenderer.invoke('clipboard-write', text),
  historyList: (limit) => ipcRenderer.invoke('history-list', limit),
  historyAppend: (entry) => ipcRenderer.invoke('history-append', entry),
  historyClear: () => ipcRenderer.invoke('history-clear'),
  listWhisperModels: () => ipcRenderer.invoke('list-whisper-models'),
  setWhisperModel: (name) => ipcRenderer.invoke('set-whisper-model', name),
  getEngine: () => ipcRenderer.invoke('get-engine'),
  setEngine: (engine) => ipcRenderer.invoke('set-engine', engine),
  getOllamaModel: () => ipcRenderer.invoke('get-ollama-model'),
  setOllamaModel: (name) => ipcRenderer.invoke('set-ollama-model', name),
  getHotkey: () => ipcRenderer.invoke('get-hotkey'),
  setHotkey: (mode) => ipcRenderer.invoke('set-hotkey', mode),
  setLanguage: (lang) => ipcRenderer.invoke('set-language', lang),
  getLanguage: () => ipcRenderer.invoke('get-language'),
  getMode: () => ipcRenderer.invoke('get-mode'),
  setMode: (mode) => ipcRenderer.invoke('set-mode', mode),
  getTone: () => ipcRenderer.invoke('get-tone'),
  setTone: (tone) => ipcRenderer.invoke('set-tone', tone),
  getTranslateTarget: () => ipcRenderer.invoke('get-translate-target'),
  setTranslateTarget: (target) => ipcRenderer.invoke('set-translate-target', target),
  getStreaming: () => ipcRenderer.invoke('get-streaming'),
  setStreaming: (enabled) => ipcRenderer.invoke('set-streaming', enabled),
  onStreamPartial: (cb) => ipcRenderer.on('stream-partial', (_e, text) => cb(text)),
  onStreamFinal: (cb) => ipcRenderer.on('stream-final', (_e, text) => cb(text)),
  onStreamError: (cb) => ipcRenderer.on('stream-error', (_e, msg) => cb(msg)),
  onStreamReady: (cb) => ipcRenderer.on('stream-ready', () => cb()),
  onToast: (cb) => ipcRenderer.on('toast', (_e, msg) => cb(msg)),
});
